// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXye00gza4cmN2I3SYP-SzWXJWxVmkFSE',
    appId: '1:1078535747697:web:e81fc609416befc54cc3d0',
    messagingSenderId: '1078535747697',
    projectId: 'tenang-test',
    authDomain: 'tenang-test.firebaseapp.com',
    storageBucket: 'tenang-test.appspot.com',
    measurementId: 'G-4NY36ECFLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2qmKZFfqT2iYDghrXK8CeFr_K0f4qnIk',
    appId: '1:1078535747697:android:e6e2d024922d29964cc3d0',
    messagingSenderId: '1078535747697',
    projectId: 'tenang-test',
    storageBucket: 'tenang-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOx0EHKM6Q_ON8M4F3fDkBmL3siW6CkE',
    appId: '1:1078535747697:ios:91aae3764e56b2494cc3d0',
    messagingSenderId: '1078535747697',
    projectId: 'tenang-test',
    storageBucket: 'tenang-test.appspot.com',
    iosClientId:
        '1078535747697-63vfan532qrs7tfa7e7u2nqaidjv5d9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenangTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPOx0EHKM6Q_ON8M4F3fDkBmL3siW6CkE',
    appId: '1:1078535747697:ios:91aae3764e56b2494cc3d0',
    messagingSenderId: '1078535747697',
    projectId: 'tenang-test',
    storageBucket: 'tenang-test.appspot.com',
    iosClientId:
        '1078535747697-63vfan532qrs7tfa7e7u2nqaidjv5d9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenangTest',
  );
}
